services:
  catalogue-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalogue
    ports:
      - 5432:5432

#  manager-db:
#    image: postgres:16
#    restart: always
#    environment:
#      POSTGRES_USER: manager
#      POSTGRES_PASSWORD: manager
#      POSTGRES_DB: manager
#    ports:
#      - 5433:5432

  selmag-keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8082:8080
    volumes:
      - .config/keycloak/import:/opt/keycloak/keycloak:23.0.4
    command: start-dev --import-realm