selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      username: service_user
      password: password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: root
    password: root

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: ouoAbI7cLQiSVWCCaBkfhKGk37yQS50E
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
